// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Antrian struct {
	ID      int32
	Tanggal time.Time
	Loket   int32
	Urut    int32
	Panggil int32
}

type User struct {
	ID       int32
	Nama     string
	Password string
}
