// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const insertAntrian = `-- name: InsertAntrian :exec
insert into antrian (loket, urut)
select
    ? AS loket,
    ifnull(max(urut),0)+1 as urut
from antrian
where date(tanggal) = current_date()
  and antrian.loket = ?
`

type InsertAntrianParams struct {
	Loket int32
}

func (q *Queries) InsertAntrian(ctx context.Context, arg InsertAntrianParams) error {
	_, err := q.db.ExecContext(ctx, insertAntrian, arg.Loket, arg.Loket)
	return err
}

const listAntrian = `-- name: ListAntrian :many
select id,loket, urut from antrian
where tanggal = current_date() and loket = ? and panggil = 0
order by urut
`

type ListAntrianRow struct {
	ID    int32
	Loket int32
	Urut  int32
}

func (q *Queries) ListAntrian(ctx context.Context, loket int32) ([]ListAntrianRow, error) {
	rows, err := q.db.QueryContext(ctx, listAntrian, loket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAntrianRow
	for rows.Next() {
		var i ListAntrianRow
		if err := rows.Scan(&i.ID, &i.Loket, &i.Urut); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selesaiAntrian = `-- name: SelesaiAntrian :exec
update antrian set panggil=1 where id = ?
`

func (q *Queries) SelesaiAntrian(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, selesaiAntrian, id)
	return err
}
