// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const ambilAntrian = `-- name: AmbilAntrian :exec
update antrian set loket = ? where id = ?
`

type AmbilAntrianParams struct {
	Loket int32
	ID    int32
}

func (q *Queries) AmbilAntrian(ctx context.Context, arg AmbilAntrianParams) error {
	_, err := q.db.ExecContext(ctx, ambilAntrian, arg.Loket, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :exec
insert into user (nama, password) values (?, ?)
`

type CreateUserParams struct {
	Nama     string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Nama, arg.Password)
	return err
}

const getAllLoket = `-- name: GetAllLoket :many

select max(urut) as urut, loket from antrian where tanggal = current_date() and panggil = 0 group by loket
`

type GetAllLoketRow struct {
	Urut  interface{}
	Loket int32
}

// select * from antrian where id = (select last_insert_id()) limit 1;
func (q *Queries) GetAllLoket(ctx context.Context) ([]GetAllLoketRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLoket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLoketRow
	for rows.Next() {
		var i GetAllLoketRow
		if err := rows.Scan(&i.Urut, &i.Loket); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAntrian = `-- name: GetAntrian :one
select id, urut, loket, DATE_FORMAT(tanggal, '%Y-%m-%d') AS tanggal from antrian
where tanggal = current_date() and id = ?
`

type GetAntrianRow struct {
	ID      int32
	Urut    int32
	Loket   int32
	Tanggal string
}

func (q *Queries) GetAntrian(ctx context.Context, id int32) (GetAntrianRow, error) {
	row := q.db.QueryRowContext(ctx, getAntrian, id)
	var i GetAntrianRow
	err := row.Scan(
		&i.ID,
		&i.Urut,
		&i.Loket,
		&i.Tanggal,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select id, nama, password from user where nama = ? limit 1
`

func (q *Queries) GetUser(ctx context.Context, nama string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, nama)
	var i User
	err := row.Scan(&i.ID, &i.Nama, &i.Password)
	return i, err
}

const insertAntrian = `-- name: InsertAntrian :execresult
insert into antrian (urut)
select
    ifnull(max(urut),0)+1 as urut
from antrian where date(tanggal) = current_date()
`

func (q *Queries) InsertAntrian(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAntrian)
}

const listAntrian = `-- name: ListAntrian :many
select id, urut, loket, DATE_FORMAT(tanggal, '%Y-%m-%d') AS tanggal from antrian
where tanggal = current_date() and panggil = 0 and loket = ?
`

type ListAntrianRow struct {
	ID      int32
	Urut    int32
	Loket   int32
	Tanggal string
}

func (q *Queries) ListAntrian(ctx context.Context, loket int32) ([]ListAntrianRow, error) {
	rows, err := q.db.QueryContext(ctx, listAntrian, loket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAntrianRow
	for rows.Next() {
		var i ListAntrianRow
		if err := rows.Scan(
			&i.ID,
			&i.Urut,
			&i.Loket,
			&i.Tanggal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mintaAntrian = `-- name: MintaAntrian :one
select id, urut, loket, DATE_FORMAT(tanggal, '%Y-%m-%d') AS tanggal from antrian
where tanggal = current_date() and panggil = 0 and loket = 0 order by id limit 1
`

type MintaAntrianRow struct {
	ID      int32
	Urut    int32
	Loket   int32
	Tanggal string
}

func (q *Queries) MintaAntrian(ctx context.Context) (MintaAntrianRow, error) {
	row := q.db.QueryRowContext(ctx, mintaAntrian)
	var i MintaAntrianRow
	err := row.Scan(
		&i.ID,
		&i.Urut,
		&i.Loket,
		&i.Tanggal,
	)
	return i, err
}

const selesaiAntrian = `-- name: SelesaiAntrian :exec
update antrian set panggil=1 where id = ?
`

func (q *Queries) SelesaiAntrian(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, selesaiAntrian, id)
	return err
}
